name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.2          
          target: esp32h2
          path: app/temp_sensor
          command: idf.py set-target esp32h2 build

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Lint C code (cppcheck)
        run: |
          cppcheck \
            --enable=warning,performance,portability \
            --error-exitcode=1 \
            --suppress=missingIncludeSystem \
            --inline-suppr \
            app/temp_sensor/main/